### ISSUE TITLE
update geom pars, iter pars in json and fit.py

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#52]
When not fitting for the geometry, instead deprojecting by a supplied geometry, I get this error.

Traceback: 
```
  Determining disc geometry
    Using your provided geometry for deprojection
    Using: inc  = -33.93 deg,
           PA   = 86.47 deg,
           dRA  = 8.63e+02 mas,
           dDec = -2.29e+02 mas
  Fitting for brightness profile
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:121: RuntimeWarning: divide by zero encountered in true_divide
  p1 = np.where(p > 0, 1. / p, 0)
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:732: RuntimeWarning: divide by zero encountered in true_divide
  beta = (self._p0 + 0.5 * (Tr1 + Tr2)) / pi - \
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:734: RuntimeWarning: divide by zero encountered in log
  pi_new = np.exp(sparse_solve(Tij_pI, beta + np.log(pi)))
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:734: RuntimeWarning: invalid value encountered in add
  pi_new = np.exp(sparse_solve(Tij_pI, beta + np.log(pi)))
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:121: RuntimeWarning: invalid value encountered in greater
  p1 = np.where(p > 0, 1. / p, 0)
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py:719: RuntimeWarning: invalid value encountered in greater
  while (np.any(np.abs(pi - pi_old) > self._tol * np.abs(pi)) and
Traceback (most recent call last):
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/fit.py", line 434, in <module>
    main()
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/fit.py", line 411, in main
    model['input_output']['iteration_diag']
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/fit.py", line 276, in perform_fit
    sol = FF.fit(u, v, vis, weights)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py", line 755, in fit
    self._ps_cov = self._ps_covariance(fit, Tij, rho)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/radial_fitters.py", line 801, in _ps_covariance
    hess_chol = scipy.linalg.cho_factor(hess)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 155, in cho_factor
    check_finite=check_finite)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 19, in _cholesky
    a1 = asarray_chkfinite(a) if check_finite else asarray(a)
  File "/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by jeffjennings** [comment]
Parameter file used to reproduce:

```
{
  "input_output" : {
    "uvtable_filename" : "",
    "load_dir"         : "",
    "save_dir"	       : "",
    "save_profile_fit" : true,
    "save_vis_fit"     : true,
    "save_uvtables"    : true,
    "iteration_diag"   : true
  },

  "modify_data" : {
    "cut_data"         : false,
    "cut_baseline"     : null
  },

  "geometry" : {
    "known_geometry"   : false,
    "fit_geometry"     : true,
    "fit_phase_offset" : true,
    "inc"              : -33.93,
    "pa"               : 86.47,
    "dra"              : 8.63e-01,
    "ddec"             : -2.29e-01
  },

  "hyperpriors" : {
    "n"                : 250,
    "rout"             : 1.6,
    "alpha"            : 1.05,
    "p0"               : 1e-15,
    "wsmooth"          : 1e-4,
    "max_iter"         : 500
  },

  "plotting" : {
    "quick_plot"       : true,
    "full_plot"        : true,
    "diag_plot"        : true,
    "save_figs"        : true,
    "dist"             : null,
    "force_style"      : true,
    "bin_widths"       : [1e3],
    "start_iter"       : 0,
    "stop_iter"        : 500
  }
}
```

**Comment by rbooth200** [comment]
I don't get this error on master branch if I save your file as tmp.json and run it as follows:
python -m frank.fit -p tmp.json -uv tutorials/AS209_continuum.npz

**Comment by rbooth200** [comment]
However your par file is suggesting to fit the geometry

**Comment by jeffjennings** [comment]
I'll update the .json par names. Set 
```
    "known_geometry"   : true,
    "fit_geometry"     : true,
    "fit_phase_offset" : true,
```
and you should see the error.

**Comment by rbooth200** [comment]
What's the reason for using such a large deviation from the phase centre here? I'm wondering if the problem is that you've shifted the origin by almost 1 arcsec

**Comment by jeffjennings** [comment]
Damn, sorry, I was providing dra, ddec in mas, not arcsec. 

Not sure if this is still a problem, but if it'll never be practically realized, then feel free to close this.

**Comment by rbooth200** [comment]
It works fine with 0,0 for the parameters. Will close
